### ISSUE TITLE
GH Pages beállítások kezelése

### ISSUE THREAD

**Issue by gradden** [Teaching-projects/SZE-MOSZE-2020-NullPointerException#6]
@hegyhati szükségünk lenne a segítségre, nem találtuk a repo beállitásait, így nem tudjuk beállítani a doxygen “.io” oldalát.

**Comment by hegyhati** [comment]
Mintha egy picit megkestetek volna ezzel, nem? :-)

**Comment by hegyhati** [comment]
(de beallitottam)

**Comment by gradden** [comment]
Koszonjuk, csak ez az aprosag volt mar hatra! :)
